before_install:
- openssl aes-256-cbc -K $encrypted_e981e1d65812_key -iv $encrypted_e981e1d65812_iv
  -in lab-devops-cloud-4aso-7db8a415381e.json.enc -out ../lab-devops-cloud-4aso-7db8a415381e.json
  -d
language: python
python:
- 3.7.9
install:
- pip install flask
script:
- python -m unittest -v test
deploy:
  provider: gae
  keyfile: /home/vagrant/lab-devops-cloud-4aso-7db8a415381e.json
  project: 510920568885
  on:
    branch: main
